#!/usr/bin/env python

import telebot

from src.bard_conversation import get_response_from_bard
from config.settings import BOT_TOKEN

bot = telebot.TeleBot(BOT_TOKEN)


@bot.message_handler(content_types=['text'], commands=['ask'])
def get_query_from_user(message):
    """
    The get_query_from_user function is a callback function that takes in the message object from the user and sends
    a message to the user asking them to ask a question. It then registers another callback function, bard_query_handler,
    to handle what happens next.

    Args:
        message: Get the chat_id of the user who sent a message to the bot

    Returns:
        A message object

    Doc Author:
        Trelent
    """
    text = 'Please ask the AI'
    sent_msg = bot.send_message(chat_id=message.chat.id, text=text, parse_mode='Markdown')
    bot.register_next_step_handler(message=sent_msg, callback=bard_query_handler)


def bard_query_handler(message):
    """
    The bard_query_handler function is the main function that handles user queries.
    It takes in a message object from the Telegram API, and returns a response to the user.
    The response is generated by calling get_response_from_bard() with input text from
    the user's query.

    Args:
        message: Get the chat_id of the user who sent the message

    Returns:
        The response from the bard model

    Doc Author:
        Trelent
    """
    while True:
        user_query = message.text
        if user_query == '/stop':
            return
        print(f'User Query :: {user_query}\n')
        user_query += '\nPlease keep it under 4096 characters.'
        bard_response = get_response_from_bard(input_text=user_query)
        bot.send_message(chat_id=message.chat.id, text="Here's your response!")
        print(f'Response :: {bard_response}')
        print('\n***********************************************************************\n')
        message = bot.send_message(chat_id=message.chat.id, text=bard_response)


def main():
    print('Starting the bot\n')
    bot.infinity_polling()
    # while True:
    #     user_input = input()
    #     if user_input:
    #         print(get_response_from_bard(input_text=user_input))
    #         print('\n***********************************************************************\n')


if __name__ == '__main__':
    main()
